### ISSUE TITLE
Highlighted letter is not always visible

### ISSUE THREAD

**Issue by niallmccullagh** [littlethunderco/animal-alphabet-issue-tracker#5]
When swiping between letters the current letter is highlighted with an underscore. However, as you keep swiping the letters on the bottom do not scroll and you no longer see the currently highlighted letter.

It might be an idea to scroll the letters on the bottom in sync with the swipes so that the highlighted letter is always on screen.

**Comment by timpotter** [comment]
Thanks Niall, we're looking into this and it will hopefully be implemented into the next release.

**Comment by timpotter** [comment]
Fixed in the latest update - v1.0.2 - available now from the App Store
